# -*- coding: utf-8 -*-
"""fooddataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pKEZFykoYNqxrISRWVC2DzKW0HcYzHv9
"""

import pandas as pd

data=pd.read_csv('indian food new.csv')

from sklearn.linear_model import LinearRegression

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(data[['index','prep_time','quantity_g']],data[['cook_time','rate_rs']])

model=LinearRegression()

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

y_pred

import matplotlib.pyplot as plt

plt.scatter(y_test,y_pred)

data.head()

data.info()

import seaborn as sns

#PLOTTING INDEPENDANT AND DEPENDANT VARIABLE
sns.pairplot(data,x_vars=['index','prep_time','quantity_g'],y_vars=['cook_time','rate_rs'],height=3,aspect=0.7)

sns.heatmap(data.corr(),annot=True)

dropdata=data.drop(['diet','region'],axis='columns')
dropdata



